name: Deploy Vehicle Microservices to EC2

on:
  push:
    branches:
      - ramaQA

jobs:
  build_and_push_images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push license-plate-validation-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/Vehicles/license-plate-validation-service
          file: ./backend/Vehicles/license-plate-validation-service/Dockerfile
          push: true
          tags: leochicaiza/license-plate-validation-service:latest

      - name: Build and push vehicle-history-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/Vehicles/vehicle-history-service
          file: ./backend/Vehicles/vehicle-history-service/Dockerfile
          push: true
          tags: leochicaiza/vehicle-history-service:latest

      - name: Build and push vehicle-registration-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/Vehicles/vehicle-registration-service
          file: ./backend/Vehicles/vehicle-registration-service/Dockerfile
          push: true
          tags: leochicaiza/vehicle-registration-service:latest

  deploy_to_ec2:
    name: Deploy Docker Containers to EC2
    runs-on: ubuntu-latest
    needs: build_and_push_images
    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST3 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # Instalar Docker si no existe
            if ! command -v docker &> /dev/null; then
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo service docker start
              sudo usermod -a -G docker ec2-user
            fi

            # Parar y eliminar contenedores anteriores
            sudo docker stop license-plate-validation-service || true
            sudo docker rm license-plate-validation-service || true
            sudo docker stop vehicle-history-service || true
            sudo docker rm vehicle-history-service || true
            sudo docker stop vehicle-registration-service || true
            sudo docker rm vehicle-registration-service || true

            # Limpiar imágenes no utilizadas
            sudo docker system prune -f

            # Pull de las nuevas imágenes
            sudo docker pull leochicaiza/license-plate-validation-service:latest
            sudo docker pull leochicaiza/vehicle-history-service:latest
            sudo docker pull leochicaiza/vehicle-registration-service:latest

            # Iniciar contenedores con puertos específicos
            sudo docker run -d \
              --name license-plate-validation-service \
              -p 8013:8013 \
              leochicaiza/license-plate-validation-service:latest

            sudo docker run -d \
              --name vehicle-history-service \
              -p 8014:8014 \
              leochicaiza/vehicle-history-service:latest

            sudo docker run -d \
              --name vehicle-registration-service \
              -p 8015:8015 \
              leochicaiza/vehicle-registration-service:latest

            # Verificar estado de los contenedores
            sudo docker ps -a

